# Generated by Django 5.0.3 on 2024-03-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataRegist', models.DateField(auto_now_add=True)),
                ('precoProduto', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
