# Generated by Django 5.0.3 on 2024-03-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafeteria_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bebida",
            name="preco",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
